name: Appelle le 1er workflow et utilise ses outputs

on:
  workflow_dispatch:

jobs:
  premier-job:
    name: Appelle le 1er workflow
    uses: ForEach-DevOps-Demo/projet-exemple/.github/workflows/outputs.yml@main

  deuxieme-job:
    name: Affiche les outputs du 1er workflow
    runs-on: ubuntu-latest
    needs: premier-job
    # needs: [premier-job, un-autre-job, encore-un]
    steps:
      - name: Retourne "Hello world!"
        run: echo ${{ needs.premier-job.outputs.variable1 }} ${{ needs.premier-job.outputs.variable2 }}
      - name: Affiche le contenu de needs
        run: echo "$NEEDS_JSON"
        env:
          NEEDS_JSON: ${{ toJSON(needs) }}
